debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.genielee.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: board-master
    password: board-postgres-password
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${SECRET_ID}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET_ID}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-authentication-method: POST
            scope:
              - name
              - email
              - nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# 암호화폐 API 설정
crypto:
  api:
    coingecko:
      base-url: https://api.coingecko.com/api/v3
      enabled: true
      timeout: 10s
      retry-attempts: 3
      rate-limit:
        requests-per-minute: 50
    upbit:
      base-url: https://api.upbit.com/v1
      enabled: true
      timeout: 10s
      retry-attempts: 3
  scheduler:
    price-update:
      enabled: true
      fixed-delay: 60000  # 1분마다 가격 업데이트
      initial-delay: 30000  # 시작 후 30초 뒤 첫 실행
    top-cryptocurrencies:
      count: 100  # 상위 100개 암호화폐 추적
  cache:
    price-ttl: 60s  # 가격 캐시 TTL

---
spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
